### ISSUE TITLE
Build Instruction

### ISSUE THREAD

**Issue by robinup** [amirtuval/vertica-hyperloglog#1]
Hi @amirtuval 

Sorry to connect you out of the blue.

I'm interested to test this Vertica UDFA, do you have a build instruction? Also if you could kindly let me know the readiness and any known issue that will be great.

thanks
Robin Li

**Comment by amirtuval** [comment]
Hi, @robinup 

Before going into the build instructions - vertica has [built in support for hyperloglog](https://my.vertica.com/docs/7.1.x/HTML/Content/Authoring/SQLReferenceManual/Functions/Aggregate/APPROXIMATE_COUNT_DISTINCT.htm). I recommend you use it, if you only need hyperloglog in vertica. The use case for my library is for when you have several systems and you want to use the same hyperloglog algorithm in all of them. For example, you want to calculate the synopsis in hadoop or spark or some other batch system, write it to vertica, and then query vertica for the (approximate) count.

In terms of readiness and stability - in my company, we've been using it in production and it works great on large amounts of data. However, I am not aware of anyone else using it, definitely not in production.
In addition, this is native code, running inside the vertica process, so a bug in it can cause catastrophic results, crashing vertica or even corrupting vertica's data.
You should definitely test all your use cases thoroughly before installing it on a production cluster.

Here are the build instructions

git clone https://github.com/amirtuval/vertica-hyperloglog.git
cd vertica-hyperloglog/
cd mysql-hyperloglog/
git submodule update --init
cd libmysqlhll/cpp-hyperloglog/
git submodule update --init
cd ../../..
make

After this, you'll have libverticahll.so under the build/ directory.

You can use sql/udf.sql to install it into vertica. Make sure you change the path to the .so file.

To get a feel for how to use the different aggregate functions, take a look at sql/example.sql which shows most of the use cases.

You can also take a look at https://github.com/amirtuval/mysql-hyperloglog. It is basically the same idea, only the readme is a little better.

Feel free to reach out if you run into trouble
Amir

**Comment by robinup** [comment]
Hi @amirtuval 

Thanks for the quick reply.

Yes, my intention is exactly to use hll across different platforms -- i.e. calculating hll synopsis from hadoop and serve it from Vertica. I've already tested your Pig HLL UDF, I think it's good, thanks ^^

However, from the build instruction, I'm running into some dependency error on the Aggregation functions (pasted below), do you see the same? Or do you have the libverticahll.so that I can download for quick test while I figure out the dependency issue?

g++  -I /opt/vertica/sdk/include -I mysql-hyperloglog/libmysqlhll -I mysql-hyperloglog/libmysqlhll/cpp-hyperloglog/include -I mysql-hyperloglog/libmysqlhll/base64 -g -Wall -Wno-unused-value -shared -fPIC  -o /home/rli/vertica-hyperloglog/build/libverticahll.so AggregateFunctions/_.cpp ScalarFunctions/_.cpp /opt/vertica/sdk/include/Vertica.cpp
In file included from mysql-hyperloglog/libmysqlhll/SerializedHyperLogLog.hpp:8,
                 from AggregateFunctions/Base.cpp:11:
mysql-hyperloglog/libmysqlhll/base64/base64.h: In function ‘char\* base64_encode(const unsigned char_, size_t, size_t_)’:
mysql-hyperloglog/libmysqlhll/base64/base64.h:26: warning: comparison between signed and unsigned integer expressions
mysql-hyperloglog/libmysqlhll/base64/base64.h:28: warning: comparison between signed and unsigned integer expressions
mysql-hyperloglog/libmysqlhll/base64/base64.h:29: warning: comparison between signed and unsigned integer expressions
mysql-hyperloglog/libmysqlhll/base64/base64.h:30: warning: comparison between signed and unsigned integer expressions
mysql-hyperloglog/libmysqlhll/base64/base64.h: In function ‘unsigned char\* base64_decode(const char_, size_t, size_t_)’:
mysql-hyperloglog/libmysqlhll/base64/base64.h:70: warning: comparison between signed and unsigned integer expressions
mysql-hyperloglog/libmysqlhll/base64/base64.h:72: warning: array subscript has type ‘char’
mysql-hyperloglog/libmysqlhll/base64/base64.h:73: warning: array subscript has type ‘char’
mysql-hyperloglog/libmysqlhll/base64/base64.h:74: warning: array subscript has type ‘char’
mysql-hyperloglog/libmysqlhll/base64/base64.h:75: warning: array subscript has type ‘char’
mysql-hyperloglog/libmysqlhll/base64/base64.h:82: warning: comparison between signed and unsigned integer expressions
mysql-hyperloglog/libmysqlhll/base64/base64.h:83: warning: comparison between signed and unsigned integer expressions
mysql-hyperloglog/libmysqlhll/base64/base64.h:84: warning: comparison between signed and unsigned integer expressions
AggregateFunctions/Base.cpp: At global scope:
AggregateFunctions/Base.cpp:16: error: ISO C++ forbids initialization of member ‘hll’
AggregateFunctions/Base.cpp:16: error: making ‘hll’ static
AggregateFunctions/Base.cpp:16: error: invalid in-class initialization of static data member of non-integral type ‘SerializedHyperLogLog_’
AggregateFunctions/Base.cpp: In member function ‘virtual void SimpleHllAggregateFunctionBase::addItem(Vertica::ServerInterface&, void_, const Vertica::VString&)’:
AggregateFunctions/Base.cpp:197: error: ‘struct HllHolder’ has no member named ‘hll’
AggregateFunctions/Base.cpp:198: error: ‘struct HllHolder’ has no member named ‘hll’
AggregateFunctions/Base.cpp:199: error: ‘struct HllHolder’ has no member named ‘hll’
AggregateFunctions/Base.cpp: In member function ‘virtual void MergeHllAggregateFunctionBase::addItem(Vertica::ServerInterface&, void_, const Vertica::VString&)’:
AggregateFunctions/Base.cpp:207: error: ‘struct HllHolder’ has no member named ‘hll’
AggregateFunctions/Base.cpp:208: error: ‘struct HllHolder’ has no member named ‘hll’
AggregateFunctions/Base.cpp:211: error: ‘struct HllHolder’ has no member named ‘hll’
AggregateFunctions/Base.cpp: In member function ‘void HllAggregateFunctionBase::updateResultFromState(Vertica::ServerInterface&, Vertica::IntermediateAggs&, void_)’:
AggregateFunctions/Base.cpp:227: error: ‘struct HllHolder’ has no member named ‘hll’
AggregateFunctions/Base.cpp:228: error: ‘struct HllHolder’ has no member named ‘hll’
AggregateFunctions/Base.cpp:231: error: ‘struct HllHolder’ has no member named ‘hll’
AggregateFunctions/Base.cpp:232: error: ‘struct HllHolder’ has no member named ‘hll’
AggregateFunctions/Base.cpp: In member function ‘void HllAggregateFunctionBase::deleteAggregateState(void_)’:
AggregateFunctions/Base.cpp:245: error: ‘struct HllHolder’ has no member named ‘hll’
AggregateFunctions/Base.cpp:246: error: ‘struct HllHolder’ has no member named ‘hll’
make: *_\* [/home/rli/vertica-hyperloglog/build/libverticahll.so] Error 1

thanks
Robin

**Comment by amirtuval** [comment]
Does not happen for me. What platform are you building this on?

In any case, what you can do if you have a little familiarity with C/C++ is go into the Base.cpp file, and change the HllHolder struct into a class with hll as a public field.

Let me know how it goes.

Thanks
Amir

**Comment by robinup** [comment]
Found the issue -- i'm using a fairly old version of complier on my box -- 
changed "SerializedHyperLogLog\* hll = NULL;" to "SerializedHyperLogLog\* hll;" it works.

I will revert back with some benchmarks.

**Comment by robinup** [comment]
Hi Amir

I run through base test cases through difference bit width, looking pretty good.

I want to confirm the appropriate way to change bit width on Pig UDF (you other project) and Vertica UDF -- as I'm running into some issue one the former.

To change precision on Pig UDF, I altered the below two files:
src/main/java/com/amirtuval/pighll/Constants.java
jni/mysql-hyperloglog/libmysqlhll/constants.hpp

To change precision on Vertica UDF, I alter the below two places:
"createHll" and "SimpleHllAggregateFunctionBase" functions in "AggregateFunctions/Base.cpp" file
mysql-hyperloglog/libmysqlhll/constants.hpp

Let me know if anything I did wrong.

Many thanks for your attention!

Have a nice weekend!

**Comment by amirtuvalyallo** [comment]
Sounds right to me.
Actually, some of the places you mentioned are redundant.

I'm afraid I iterated through this code pretty quickly and did not take the time to cleanup irrelevant old code so it is a bit confusing.

I did not have time to test, but looking at the code it seems to me that 

for vertica - 
you only need "createHll" in "SimpleHllAggregateFunctionBase" class in "AggregateFunctions/Base.cpp" file

for pig - 
you only need to change src/main/java/com/amirtuval/pighll/Constants.java

Again, did not have time to test, just browsed the code, so I might have missed something.

Let me know how it goes
Amir

**Comment by robinup** [comment]
Sounds good, I will have a full test result for you by early next week.

**Comment by robinup** [comment]
Hi Amir

I'm writing just to confirm your comments above is working as expected.

However, a quick side note - line 47 in the below file is too small, will
break segmentation when constant is over 13. Changed this to a large number
works well.
pig-hyperloglog/jni/pighll.cxx

On Mon, Apr 11, 2016 at 1:00 PM, amirtuvalyallo notifications@github.com
wrote:

> Sounds right to me.
> Actually, some of the places you mentioned are redundant.
> 
> I'm afraid I iterated through this code pretty quickly and did not take
> the time to cleanup irrelevant old code so it is a bit confusing.
> 
> I did not have time to test, but looking at the code it seems to me that
> 
> for vertica -
> you only need "createHll" in "SimpleHllAggregateFunctionBase" class in
> "AggregateFunctions/Base.cpp" file
> 
> for pig -
> you only need to change src/main/java/com/amirtuval/pighll/Constants.java
> 
> Again, did not have time to test, just browsed the code, so I might have
> missed something.
> 
> Let me know how it goes
> Amir
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/amirtuval/vertica-hyperloglog/issues/1#issuecomment-208531099

## 

Robin
